id: P010466
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC28
  title: འགྲེལ་པ་དོན་གསལ།
  author: ''
  volumes:
    1a570504c8f642a58a49edc20055b131:
      image_group_id: I2PD18851
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
